name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: npm install
        run: npm ci

      - name: lint
        run: npm run lint --quiet

      - name: typecheck
        run: npm run typecheck

  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [ 20, 22 ]
        os: [ ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup node ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: npm install
      run: npm ci

    - name: test
      run: npm test
      env:
        CI: true

    - name: build
      run: npm run build
